### ISSUE TITLE
Udeploy is not pulling the details 

### ISSUE THREAD

**Issue by anayyadav** [Hygieia/hygieia-deploy-udeploy-collector#4]
Hi friends,

I have configured Udeploy collector and I am getting data for an application but when I have configured Udeploy widget for another application named 'CommercialGateway' I did not get any data on UI.
The strange thing is I am not getting any error in logs. 
Please share any solution if you have. 

Here are the screenshots:
![ucderror](https://user-images.githubusercontent.com/22302511/57755998-eca59480-770f-11e9-87c5-66e993f4dd2e.PNG)
![ucderror1](https://user-images.githubusercontent.com/22302511/57756009-f3cca280-770f-11e9-989b-e2550f72ec62.PNG)
![ucd2](https://user-images.githubusercontent.com/22302511/57756058-12cb3480-7710-11e9-948c-3f7ab28eb0b9.PNG)

**Comment by Priya123-lang** [comment]
Hi,

I have configured uDeloy Collector ,it's pulling the application but after selecting the application the respective details are not getting pulled into UI. Also where does this application list from uDeploy gets stored in MongoDB  and the deployment details also under which documents it's get stored? 

Currently am using UCD version 6.2.4

Have anyone faced this issue and any solution for this?

**Comment by yalalasai** [comment]
Hi @Priya123-lang, Did you get any solution for this..?

**Comment by Priya123-lang** [comment]
Hi @yalalasai , need to have details in all 4 rest api's that we can see in code logic. Inventory components should hold the details and the resource version in filetree rest api. Only then we are able to see the data in UI..

**Comment by yalalasai** [comment]
> Hi @yalalasai , need to have details in all 4 rest api's that we can see in code logic. Inventory components should hold the details and the resource version in filetree rest api. Only then we are able to see the data in UI..

@Priya123-lang  can you please help me in understanding this?
